Repository WildCodeSchool-2024-02/JS-RemoteFR-CrewDragon-P3-StreetArtHunter, pull requests merged in 2024-06, with the labels that each got.

#4 Gal
  client/package.json
  client/src/App.jsx
  client/src/assets/streetAve.jpg
  client/src/assets/streetElephant.jpg
  client/src/assets/streetWash.jpg
  client/src/assets/streetWoman.jpg
  client/src/components/Nav.jsx
  client/src/data/tempGaleryData.js
  client/src/main.jsx
  client/src/main.scss
  client/src/pages/Galery.jsx
  client/src/pages/Home.jsx
  client/src/style/galery.scss
Labels: REVIEW REQUESTED

#5 Home fab
  client/src/components/PopupConnexion.jsx
  client/src/components/PopupInscription.jsx
  client/src/pages/Home.jsx
Labels: REVIEWED

#7 Add map component
  client/package.json
  client/src/App.jsx
  client/src/components/Map.jsx
  client/src/main.jsx
Labels: REVIEW REQUESTED

#8 Added background color and gradients
  client/src/assets/Blue-Gradient.svg
  client/src/assets/Orange-Gradient.svg
  client/src/main.scss
Labels: REVIEW REQUESTED

#6 start style
  client/src/main.scss
Labels: REVIEW REQUESTED

#13 Je suis tatillon
  client/src/style/Footer.scss
Labels: REVIEW REQUESTED

#14 le boutton regle envoie sur instruction
  client/src/pages/Home.jsx
Labels: REVIEW REQUESTED

#15 Update README.md
  README.md
Labels: REVIEWED

#16 Header root css
  client/src/main.scss
  client/src/style/Header.scss
  client/src/style/galery.scss
Labels: REVIEWED

#17 css to map
  client/src/components/Map.jsx
  client/src/main.scss
  client/src/pages/Home.jsx
  client/src/pages/Insctruction.jsx
  client/src/style/home.scss
  client/src/style/instruction.scss
  client/src/style/map.scss
Labels: REVIEWED

#18 Fonts added
  client/src/assets/fonts/Athiti-Regular.ttf
  client/src/assets/fonts/PressStart2P-Regular.ttf
  client/src/assets/fonts/VT323-Regular.ttf
  client/src/components/Header.jsx
  client/src/main.scss
Labels: REVIEW REQUESTED

#20 little fix
  client/src/main.scss
  client/src/style/Header.scss
Labels: REVIEW REQUESTED, REVIEWED

#21 Maplocation
  client/src/App.jsx
  client/src/components/IconMap.jsx
  client/src/components/LocationMarker.jsx
  client/src/components/Map.jsx
  client/src/main.scss
  client/src/pages/Home.jsx
  client/src/style/map.scss
Labels: REVIEW REQUESTED

#22 fix import css
  client/src/components/Header.jsx
  client/src/components/Map.jsx
  client/src/main.scss
  client/src/style/home.scss
Labels: REVIEW REQUESTED

#24 fixed burger feature
  client/src/components/Header.jsx
Labels: REVIEWED

#25 Harmonize global style
  client/src/App.jsx
  client/src/assets/Dark-Button.svg
  client/src/assets/Dark-Button_hover.svg
  client/src/assets/Light-Button.svg
  client/src/assets/Light-Button_hover.svg
  client/src/assets/fonts/Athiti-Bold.ttf
  client/src/assets/fonts/Athiti-Medium.ttf
  client/src/assets/graffiti.2.png
  client/src/assets/graffiti.3.png
  client/src/components/Footer.jsx
  client/src/components/Header.jsx
  client/src/components/Nav.jsx
  client/src/main.scss
  client/src/pages/Galery.jsx
  client/src/pages/Home.jsx
  client/src/pages/Insctruction.jsx
  client/src/style/Footer.scss
  client/src/style/Header.scss
  client/src/style/burger.scss
  client/src/style/galery.scss
  client/src/style/instruction.scss
  client/src/style/map.scss
  client/src/style/nav.scss
Labels: REVIEW REQUESTED, REVIEWED

#30 Field access
  client/src/components/PopupConnexion.jsx
  client/src/components/PopupInscription.jsx
  client/src/style/popup.scss
Labels: REVIEW REQUESTED, REVIEWED

#31 Fix.style
  client/src/components/Map.jsx
  client/src/main.scss
  client/src/pages/Home.jsx
  client/src/style/Header.scss
  client/src/style/burger.scss
  client/src/style/home.scss
  client/src/style/map.scss
Labels: REVIEW REQUESTED, REVIEWED

#34 Fix SCSS to burger
  client/src/style/burger.scss
Labels: REVIEW REQUESTED

#37 Fix.css
  client/src/assets/Close-Button.svg
  client/src/components/Nav.jsx
  client/src/components/PopupConnexion.jsx
  client/src/components/PopupInscription.jsx
  client/src/main.scss
  client/src/pages/Home.jsx
  client/src/style/burger.scss
  client/src/style/home.scss
  client/src/style/nav.scss
  client/src/style/popup.scss
Labels: REVIEW REQUESTED

#39 Add scss and marker leaflet
  client/index.html
  client/src/assets/Close-Button.svg
  client/src/assets/Logo_SAH_P3_IF.png
  client/src/assets/graffiti.3.png
  client/src/assets/graffiti.3_25x27px.ico
  client/src/components/GeolocWorkArt.jsx
  client/src/components/IconMap.jsx
  client/src/components/Map.jsx
  client/src/components/Nav.jsx
  client/src/components/PopupConnexion.jsx
  client/src/components/PopupInscription.jsx
  client/src/main.scss
  client/src/pages/Admin.jsx
  client/src/pages/Home.jsx
  client/src/style/Footer.scss
  client/src/style/Header.scss
  client/src/style/burger.scss
  client/src/style/galery.scss
  client/src/style/home.scss
  client/src/style/map.scss
  client/src/style/nav.scss
  client/src/style/popup.scss
  server/app/config.js
  server/package.json
Labels: REVIEWED

#41 create database tables
  server/database/schema.sql
Labels: REVIEW REQUESTED

#44 set MCV for picture: sujet a changement selon nos besoin
  server/app/controllers/pictureActions.js
  server/app/routers/api/pictures/router.js
  server/database/models/PictureRepository.js
Labels: REVIEWED

#43 mvc artist done
  server/app/controllers/ArtistAction.js
  server/app/routers/api/artist/router.js
  server/app/routers/api/router.js
  server/database/models/ArtistRepository.js
Labels: REVIEWED

#45 Fix button behavior in home page
  client/src/components/PopupConnexion.jsx
  client/src/components/PopupInscription.jsx
  client/src/main.scss
  client/src/pages/Home.jsx
  client/src/pages/Insctruction.jsx
  client/src/style/popup.scss
Labels: REVIEW REQUESTED

#46 add table Person
  client/src/components/Map.jsx
  server/app/controllers/personActions.js
  server/database/models/PersonRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: REVIEW REQUESTED

#48 adding artistartwork table de jointure
  server/app/controllers/ArtistArtworkAction.js
  server/app/routers/api/artistartwork/router.js
  server/app/routers/api/router.js
  server/database/models/ArtistArtworkRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: REVIEW REQUESTED

#47 mvc for artwork
  server/app/controllers/ArtworkAction.js
  server/app/routers/api/artworks/router.js
  server/app/routers/api/router.js
  server/database/models/ArtworkRepository.js
  server/database/tables.js
Labels: CORRECTIONS DONE, REVIEWED

#51 Fix
  server/app/routers/api/artists/router.js
  server/app/routers/api/router.js
  server/database/schema.sql
Labels: REVIEW REQUESTED

#50 MEP 21/06
  client/src/components/Map.jsx
  client/src/components/PopupConnexion.jsx
  client/src/components/PopupInscription.jsx
  client/src/main.scss
  client/src/pages/Home.jsx
  client/src/pages/Insctruction.jsx
  client/src/style/galery.scss
  client/src/style/popup.scss
  server/app/controllers/ArtistAction.js
  server/app/controllers/ArtistArtworkAction.js
  server/app/controllers/ArtworkAction.js
  server/app/controllers/personActions.js
  server/app/controllers/pictureActions.js
  server/app/controllers/roleActions.js
  server/app/routers/api/artistartwork/router.js
  server/app/routers/api/artists/router.js
  server/app/routers/api/artworks/router.js
  server/app/routers/api/persons/router.js
  server/app/routers/api/pictures/router.js
  server/app/routers/api/roles/router.js
  server/app/routers/api/router.js
  server/database/models/ArtistArtworkRepository.js
  server/database/models/ArtistRepository.js
  server/database/models/ArtworkRepository.js
  server/database/models/PersonRepository.js
  server/database/models/PictureRepository.js
  server/database/models/RoleRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: CORRECTIONS DONE, REVIEWED

#53 updated css and organised files
  client/index.html
  client/src/assets/.gitkeep
  client/src/assets/favicon.ico
  client/src/assets/graffiti.3.png
  client/src/assets/icons/favicon_sah.ico
  client/src/assets/icons/logo_sah.png
  client/src/assets/icons/marker_sah.png
  client/src/assets/logo.png
  client/src/assets/patterns/Blue-Gradient.svg
  client/src/assets/patterns/Burger-Menu-Mobile.svg
  client/src/assets/patterns/Burger-Menu.svg
  client/src/assets/patterns/Close-Button.svg
  client/src/assets/patterns/Dark-Button.svg
  client/src/assets/patterns/Dark-Button_hover.svg
  client/src/assets/patterns/Light-Button.svg
  client/src/assets/patterns/Light-Button_hover.svg
  client/src/assets/patterns/Orange-Gradient.svg
  client/src/assets/pictures/streetAve.jpg
  client/src/assets/pictures/streetElephant.jpg
  client/src/assets/pictures/streetWash.jpg
  client/src/assets/pictures/streetWoman.jpg
  client/src/components/.gitkeep
  client/src/components/Burger.jsx
  client/src/components/Header.jsx
  client/src/components/IconMap.jsx
  client/src/components/LocationMarker.jsx
  client/src/components/PopupConnexion.jsx
  client/src/components/PopupInscription.jsx
  client/src/data/tempGaleryData.js
  client/src/main.scss
  client/src/pages/.gitkeep
  client/src/pages/Home.jsx
  client/src/style/Header.scss
  client/src/style/home.scss
  client/src/style/map.scss
  client/src/style/nav.scss
  server/database/models/PersonRepository.js
Labels: REVIEWED

#54 Popup
  client/src/components/Nav.jsx
  client/src/components/PopupConnexion.jsx
  client/src/components/PopupInscription.jsx
  client/src/style/popup.scss
  package-lock.json
Labels: REVIEW REQUESTED

#58 Fix test for connexion
  server/app/controllers/personActions.js
  server/app/routers/api/persons/router.js
  server/tests/connexion/connexion.spec.js
Labels: REVIEW REQUESTED

#60 fix testCo with auth
  server/app/controllers/authActions.js
  server/app/controllers/personActions.js
  server/app/routers/api/persons/router.js
  server/database/models/PersonRepository.js
  server/database/schema.sql
  server/tests/connexion/connexion.spec.js
Labels: REVIEW REQUESTED

#61 Fix pop up and harmonize style
  client/src/App.jsx
  client/src/components/Header.jsx
  client/src/components/Nav.jsx
  client/src/main.jsx
  client/src/main.scss
  client/src/pages/Galery.jsx
  client/src/pages/Home.jsx
  client/src/pages/PopupConnexion.jsx
  client/src/pages/PopupInscription.jsx
  client/src/style/Footer.scss
  client/src/style/Header.scss
  client/src/style/burger.scss
  client/src/style/home.scss
  client/src/style/nav.scss
  client/src/style/popup.scss
Labels: REVIEW REQUESTED

#62 Test artwor
  server/app/controllers/ArtworkAction.js
  server/tests/ArtworkCreation/createArt.spec.js
  server/tests/connexion/connexion.spec.js
Labels: REVIEWED

#63 Momo jebri
  client/src/components/Webcam.jsx
  client/src/pages/Home.jsx
  client/src/style/Webcam.scss
  client/src/style/popup.scss
Labels: REVIEW REQUESTED

#64 Create review
  server/app/controllers/reviewActions.js
  server/app/routers/api/review/router.js
  server/database/models/ReviewRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: REVIEW REQUESTED

#65 Fix: table picture
  server/database/schema.sql
Labels: REVIEW REQUESTED

#66 add userpage
  client/src/components/Nav.jsx
  client/src/main.jsx
  client/src/pages/Home.jsx
  client/src/pages/User.jsx
  client/src/pages/Users.jsx
  client/src/style/Webcam.scss
Labels: REVIEW REQUESTED

#67 Fix: route for review
  server/app/routers/api/router.js
Labels: REVIEW REQUESTED

#69 fix user dashboard
  client/src/components/Webcam.jsx
  client/src/pages/User.jsx
Labels: REVIEW REQUESTED
